### ISSUE TITLE
New maintainer requested

### ISSUE THREAD

**Issue by davidread** [bellisk/ckanext-subscribe#4]
I'm not involved in CKAN for the past couple of years and would appreciate a new maintainer to come forward to nurture it for the benefit of the community.

I see that there are 2 forks with commits in the past couple of years:

* [opendata-swiss](https://github.com/opendata-swiss/ckanext-subscribe) - @bellisk
* [opengov-opendata](https://github.com/OpenGov-OpenData/ckanext-subscribe) - @peterVorman @jguo144 @javier-tello

Would either of these orgs be willing to take this on?

I get that both of the orgs may have done some customizations on their fork that is specific to their own setup, rather than being general. There's no reason though that an org can keep a fork too with their customizations. The trunk should ideally stay general and customizable. It's great to see the ISubscribe interface approach from @bellisk. And I see there's an extensive change to support CKAN 2.9 from OpenGov: https://github.com/isabella232/ckanext-subscribe/commit/11188d4e1371143ee5c8f21810c5a0cc6143a60c which seems like a key feature to make available in the trunk.

It would be great to hear your thoughts on this.

**Comment by bellisk** [comment]
Hi David, sorry for the late reply on this! I would be happy to take on a maintainer role for this repo, since we are using it for opendata.swiss.

If it's OK with you, my teammates @kovalch and @stefina could also join - since all three of us are working with CKAN and this ckanext, we could spread the load a bit that way.

**Comment by davidread** [comment]
Many thanks @bellisk. Repository transfer to bellisk request now sent.

**Comment by davidread** [comment]
Maintainership has now passed to @bellisk. Regards, David
